_target_: datasets.bsd.BSDLDM
batch_size: 128
num_workers: 8
sampling_freq: 1000
sample_len: 20
min_num_sample: 5
max_num_sample: 10
delay_between_sample: 10
num_sample_per_epoch: 8000
S: 200
n_channels: 10
num_classes: 20 # Number of classes
n_common_channels: 3
t: 20
dt: 0.1
spike_prob_min: 0.05
spike_prob_max: 0.8
val_split: 0.1
test_split: 0.2
