_target_: datasets.ssc.SSCLDM
data_path: ${datadir}
spatial_factor: 0.2
time_factor: 0.001
window_size: 4
batch_size: 256
num_workers: 8
num_classes: 35
pad_to_min_size: 300
ignore_first_timesteps: 10